// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFslks0l7eauR9uHdK6sHadQuRVvHwJjg',
    appId: '1:706032254448:web:64fbce2bba5ceaea707135',
    messagingSenderId: '706032254448',
    projectId: 'goat-farm-manager-26d40',
    authDomain: 'goat-farm-manager-26d40.firebaseapp.com',
    storageBucket: 'goat-farm-manager-26d40.appspot.com',
    measurementId: 'G-8J09DKWJEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJGMGlqW4AxNzniOXsJdE19kafFYWz1s',
    appId: '1:706032254448:android:35fd822c80eb7bb9707135',
    messagingSenderId: '706032254448',
    projectId: 'goat-farm-manager-26d40',
    storageBucket: 'goat-farm-manager-26d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PW0AFrYqcs4DYb0phAamt-xlK1YMv_4',
    appId: '1:706032254448:ios:01b85a2344c4a1f0707135',
    messagingSenderId: '706032254448',
    projectId: 'goat-farm-manager-26d40',
    storageBucket: 'goat-farm-manager-26d40.appspot.com',
    iosBundleId: 'com.example.goatFarmManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PW0AFrYqcs4DYb0phAamt-xlK1YMv_4',
    appId: '1:706032254448:ios:3484a90e1e88d269707135',
    messagingSenderId: '706032254448',
    projectId: 'goat-farm-manager-26d40',
    storageBucket: 'goat-farm-manager-26d40.appspot.com',
    iosBundleId: 'com.example.goatFarmManager.RunnerTests',
  );
}
